
services:
  db:
    image: postgres
    restart: always

    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: phonebook
    ports:
      - "5432:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: